# Generated by Django 5.1.6 on 2025-02-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField()),
                ("body_mail", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Рассылка будет отправлена на указанный email.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                ("full_name", models.CharField(max_length=30, verbose_name="Ф.И.О")),
                ("comment", models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Mailling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDt", models.DateField()),
                ("endDt", models.DateField()),
                (
                    "my_field",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NEW",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailling.mail"
                    ),
                ),
                ("recipient", models.ManyToManyField(to="mailling.recipient")),
            ],
        ),
        migrations.CreateModel(
            name="TryRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_try", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")]
                    ),
                ),
                ("mail_response", models.TextField()),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailling.recipient",
                    ),
                ),
            ],
        ),
    ]
