# Generated by Django 5.1.6 on 2025-02-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="body_mail",
            field=models.TextField(verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="mail",
            name="theme",
            field=models.CharField(max_length=50, verbose_name="Тема письма"),
        ),
        migrations.AlterField(
            model_name="mailling",
            name="endDt",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailling",
            name="mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailling.mail",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailling",
            name="my_field",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="Создана",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailling",
            name="recipient",
            field=models.ManyToManyField(
                to="mailling.recipient", verbose_name="Получатель"
            ),
        ),
        migrations.AlterField(
            model_name="mailling",
            name="startDt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=50, verbose_name="Ф.И.О"),
        ),
        migrations.AlterField(
            model_name="tryrecipient",
            name="mail_response",
            field=models.TextField(verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="tryrecipient",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailling.recipient",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="tryrecipient",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                default="Успешно",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="tryrecipient",
            name="time_try",
            field=models.DateTimeField(verbose_name="Дата и время попытки"),
        ),
    ]
